/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ftc_vision_OpencvNativeClass */

#ifndef _Included_ftc_vision_OpencvNativeClass
#define _Included_ftc_vision_OpencvNativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ftc_vision_OpencvNativeClass
 * Method:    convertGray
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ftc_vision_OpencvNativeClass_convertGray
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
