/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <opencv2/opencv.hpp>

using namespace cv;
using namespace std;
/* Header for class ftc_vision_OpencvNativeClass */

#ifndef _Included_ftc_vision_OpencvNativeClass
#define _Included_ftc_vision_OpencvNativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ftc_vision_OpencvNativeClass
 * Method:    convertGray
 * Signature: (JJ)I
 */
KeyPoint toGray(Mat img, Mat& gray,bool blueside);
void calibrate();


static int bestBallX = 1;
static int bestBallY = 1;
static int bestBallRadius = 1;
static int minH = 93;
static int minS = 100;
static int minV = 10;
static int maxH = 105;
static int maxS = 255;
static int maxV = 255;



static int avH =108;
static int avS = 221;
static int avV = 95;

static Mat currentImage;




JNIEXPORT void JNICALL Java_ftc_vision_OpencvNativeClass_convertGray
  (JNIEnv * , jclass, jlong, jlong,jboolean);

JNIEXPORT void JNICALL Java_ftc_vision_OpencvNativeClass_calibrate
(JNIEnv * , jclass);

#ifdef __cplusplus
}
#endif
#endif
